export interface ThemeDefinition {
  id: string;
  name: string;
  category: "Archival & Editorial" | "Prestigious Universities" | "Modern Minimalist" | "Earth & Nature" | "Scholarly Night";
  isPinned?: boolean;
  description: string;
  swatch: {
    canvas: string;
    card: string;
    accent: string;
  };
  fontHeading: "serif" | "sans";
  cssVars: {
    bgCanvas: string;
    bgCard: string;
    bgSubtle: string;
    borderColor: string;
    textMain: string;
    textMuted: string;
    accentPrimary: string;
    accentHover: string;
    accentSubtle: string;
    badgeBg: string;
    badgeText: string;
  };
}

export const ACADEMIC_THEMES: Record<string, ThemeDefinition> = {
  // 1. Archival & Editorial
  "cream-terracotta": {
    id: "cream-terracotta",
    name: "Warm Cream & Terracotta",
    category: "Archival & Editorial",
    isPinned: true,
    description: "Archival book paper canvas with warm terracotta saddle bronze accents.",
    swatch: { canvas: "#faf7f2", card: "#ffffff", accent: "#8a4b2d" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#faf7f2",
      bgCard: "#ffffff",
      bgSubtle: "#f3ede3",
      borderColor: "#e8e2d8",
      textMain: "#2c2b29",
      textMuted: "#666056",
      accentPrimary: "#8a4b2d",
      accentHover: "#723c22",
      accentSubtle: "rgba(138, 75, 45, 0.08)",
      badgeBg: "rgba(138, 75, 45, 0.1)",
      badgeText: "#8a4b2d",
    },
  },
  "sand-forest": {
    id: "sand-forest",
    name: "Muted Sand & Forest Olive",
    category: "Archival & Editorial",
    isPinned: true,
    description: "Organic parchment sand canvas with distinguished British racing green accents.",
    swatch: { canvas: "#f4efe6", card: "#ffffff", accent: "#284e3a" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f4efe6",
      bgCard: "#ffffff",
      bgSubtle: "#ebe3d5",
      borderColor: "#ded6c7",
      textMain: "#242926",
      textMuted: "#525c56",
      accentPrimary: "#284e3a",
      accentHover: "#1f3d2e",
      accentSubtle: "rgba(40, 78, 58, 0.08)",
      badgeBg: "rgba(40, 78, 58, 0.1)",
      badgeText: "#284e3a",
    },
  },
  "parchment-umber": {
    id: "parchment-umber",
    name: "Classical Parchment & Umber",
    category: "Archival & Editorial",
    description: "Ancient library parchment tone with deep raw umber typography.",
    swatch: { canvas: "#f9f6ef", card: "#ffffff", accent: "#634735" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f9f6ef",
      bgCard: "#ffffff",
      bgSubtle: "#efe9dc",
      borderColor: "#e3dcce",
      textMain: "#2e2924",
      textMuted: "#6b6359",
      accentPrimary: "#634735",
      accentHover: "#4e3526",
      accentSubtle: "rgba(99, 71, 53, 0.08)",
      badgeBg: "rgba(99, 71, 53, 0.1)",
      badgeText: "#634735",
    },
  },
  "tuscan-clay": {
    id: "tuscan-clay",
    name: "Tuscan Wheat & Clay",
    category: "Archival & Editorial",
    description: "Sun-drenched Mediterranean paper with warm terracotta brick accents.",
    swatch: { canvas: "#f7f3ec", card: "#ffffff", accent: "#9c5333" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f7f3ec",
      bgCard: "#ffffff",
      bgSubtle: "#eee5d8",
      borderColor: "#e2d7c5",
      textMain: "#2c2621",
      textMuted: "#66594f",
      accentPrimary: "#9c5333",
      accentHover: "#824125",
      accentSubtle: "rgba(156, 83, 51, 0.08)",
      badgeBg: "rgba(156, 83, 51, 0.1)",
      badgeText: "#9c5333",
    },
  },

  // 2. Prestigious Universities
  "stone-oxford": {
    id: "stone-oxford",
    name: "Limestone & Oxford Navy",
    category: "Prestigious Universities",
    description: "Pale chalk limestone with formal Royal Oxford academic navy.",
    swatch: { canvas: "#f5f6f8", card: "#ffffff", accent: "#1b365d" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f5f6f8",
      bgCard: "#ffffff",
      bgSubtle: "#e9ecf2",
      borderColor: "#dbe0eb",
      textMain: "#1e242d",
      textMuted: "#515e70",
      accentPrimary: "#1b365d",
      accentHover: "#142846",
      accentSubtle: "rgba(27, 54, 93, 0.08)",
      badgeBg: "rgba(27, 54, 93, 0.1)",
      badgeText: "#1b365d",
    },
  },
  "linen-crimson": {
    id: "linen-crimson",
    name: "French Linen & Harvard Crimson",
    category: "Prestigious Universities",
    description: "Warm woven linen canvas with vintage Harvard wine crimson accents.",
    swatch: { canvas: "#f8f5f0", card: "#ffffff", accent: "#80222f" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f8f5f0",
      bgCard: "#ffffff",
      bgSubtle: "#efe6dc",
      borderColor: "#ebdcd8",
      textMain: "#2c2627",
      textMuted: "#635557",
      accentPrimary: "#80222f",
      accentHover: "#681924",
      accentSubtle: "rgba(128, 34, 47, 0.08)",
      badgeBg: "rgba(128, 34, 47, 0.1)",
      badgeText: "#80222f",
    },
  },
  "cambridge-cobalt": {
    id: "cambridge-cobalt",
    name: "Cambridge Stone & Cobalt",
    category: "Prestigious Universities",
    description: "British university stone gray with vibrant Cambridge academic blue.",
    swatch: { canvas: "#f3f5f8", card: "#ffffff", accent: "#1a447a" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f3f5f8",
      bgCard: "#ffffff",
      bgSubtle: "#e4e9f0",
      borderColor: "#d5dde7",
      textMain: "#1c222b",
      textMuted: "#505b6b",
      accentPrimary: "#1a447a",
      accentHover: "#13345e",
      accentSubtle: "rgba(26, 68, 122, 0.08)",
      badgeBg: "rgba(26, 68, 122, 0.1)",
      badgeText: "#1a447a",
    },
  },
  "imperial-purple": {
    id: "imperial-purple",
    name: "Imperial Slate & Regal Violet",
    category: "Prestigious Universities",
    description: "Pale lavender mist canvas with distinguished scholarly violet.",
    swatch: { canvas: "#f6f4f8", card: "#ffffff", accent: "#59316b" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f6f4f8",
      bgCard: "#ffffff",
      bgSubtle: "#ebe6f0",
      borderColor: "#ded6e5",
      textMain: "#251f28",
      textMuted: "#5f5366",
      accentPrimary: "#59316b",
      accentHover: "#462454",
      accentSubtle: "rgba(89, 49, 107, 0.08)",
      badgeBg: "rgba(89, 49, 107, 0.1)",
      badgeText: "#59316b",
    },
  },

  // 3. Modern Minimalist
  "nordic-snow": {
    id: "nordic-snow",
    name: "Nordic Snow & Charcoal",
    category: "Modern Minimalist",
    description: "Ultra-clean pure minimalist canvas with refined graphite typography.",
    swatch: { canvas: "#fbfbfb", card: "#ffffff", accent: "#18181b" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#fbfbfb",
      bgCard: "#ffffff",
      bgSubtle: "#f1f1f1",
      borderColor: "#e4e4e7",
      textMain: "#18181b",
      textMuted: "#71717a",
      accentPrimary: "#18181b",
      accentHover: "#000000",
      accentSubtle: "rgba(24, 24, 27, 0.06)",
      badgeBg: "rgba(24, 24, 27, 0.08)",
      badgeText: "#18181b",
    },
  },
  "notion-sage": {
    id: "notion-sage",
    name: "Notion Warm & Sage Green",
    category: "Modern Minimalist",
    description: "Calm productivity aesthetic with soft Japanese tea sage green.",
    swatch: { canvas: "#f8f9f7", card: "#ffffff", accent: "#3e624c" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#f8f9f7",
      bgCard: "#ffffff",
      bgSubtle: "#eef1ec",
      borderColor: "#e1e6de",
      textMain: "#222a25",
      textMuted: "#59665e",
      accentPrimary: "#3e624c",
      accentHover: "#2e4a39",
      accentSubtle: "rgba(62, 98, 76, 0.08)",
      badgeBg: "rgba(62, 98, 76, 0.1)",
      badgeText: "#3e624c",
    },
  },
  "cashmere-espresso": {
    id: "cashmere-espresso",
    name: "Cashmere & Espresso Noir",
    category: "Modern Minimalist",
    description: "Quiet luxury cashmere beige with roasted espresso and walnut.",
    swatch: { canvas: "#f6f3ed", card: "#ffffff", accent: "#3d322a" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f6f3ed",
      bgCard: "#ffffff",
      bgSubtle: "#ebe5da",
      borderColor: "#ded6c7",
      textMain: "#24211e",
      textMuted: "#5e564d",
      accentPrimary: "#3d322a",
      accentHover: "#2c231c",
      accentSubtle: "rgba(61, 50, 42, 0.08)",
      badgeBg: "rgba(61, 50, 42, 0.1)",
      badgeText: "#3d322a",
    },
  },
  "zinc-steel": {
    id: "zinc-steel",
    name: "Zinc Minimalist & Steel Blue",
    category: "Modern Minimalist",
    description: "Industrial engineering zinc with cool technical steel blue.",
    swatch: { canvas: "#f4f5f7", card: "#ffffff", accent: "#2c4866" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#f4f5f7",
      bgCard: "#ffffff",
      bgSubtle: "#e8eaef",
      borderColor: "#d9dce3",
      textMain: "#1f262f",
      textMuted: "#55606e",
      accentPrimary: "#2c4866",
      accentHover: "#1f344a",
      accentSubtle: "rgba(44, 72, 102, 0.08)",
      badgeBg: "rgba(44, 72, 102, 0.1)",
      badgeText: "#2c4866",
    },
  },

  // 4. Earth & Nature
  "matcha-moss": {
    id: "matcha-moss",
    name: "Matcha Green & Moss",
    category: "Earth & Nature",
    description: "Earthy organic botanical canvas with deep moss garden tones.",
    swatch: { canvas: "#f5f7f4", card: "#ffffff", accent: "#2e5339" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f5f7f4",
      bgCard: "#ffffff",
      bgSubtle: "#e7ede5",
      borderColor: "#d6e0d3",
      textMain: "#212b23",
      textMuted: "#536357",
      accentPrimary: "#2e5339",
      accentHover: "#223d2b",
      accentSubtle: "rgba(46, 83, 57, 0.08)",
      badgeBg: "rgba(46, 83, 57, 0.1)",
      badgeText: "#2e5339",
    },
  },
  "pacific-teal": {
    id: "pacific-teal",
    name: "Pacific Coast & Ocean Teal",
    category: "Earth & Nature",
    description: "Crisp coastal ocean mist canvas with deep deep-sea teal accents.",
    swatch: { canvas: "#f3f7f7", card: "#ffffff", accent: "#1e5b61" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#f3f7f7",
      bgCard: "#ffffff",
      bgSubtle: "#e3eeef",
      borderColor: "#d1e2e3",
      textMain: "#1b2829",
      textMuted: "#4f6567",
      accentPrimary: "#1e5b61",
      accentHover: "#154145",
      accentSubtle: "rgba(30, 91, 97, 0.08)",
      badgeBg: "rgba(30, 91, 97, 0.1)",
      badgeText: "#1e5b61",
    },
  },
  "autumn-rust": {
    id: "autumn-rust",
    name: "Autumn Cedar & Amber Rust",
    category: "Earth & Nature",
    description: "Warm cedar bark canvas with glowing autumnal rust accents.",
    swatch: { canvas: "#f9f6f3", card: "#ffffff", accent: "#a04c27" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f9f6f3",
      bgCard: "#ffffff",
      bgSubtle: "#f0e8e0",
      borderColor: "#e4d8cc",
      textMain: "#2e241e",
      textMuted: "#69574c",
      accentPrimary: "#a04c27",
      accentHover: "#823c1d",
      accentSubtle: "rgba(160, 76, 39, 0.08)",
      badgeBg: "rgba(160, 76, 39, 0.1)",
      badgeText: "#a04c27",
    },
  },
  "desert-agave": {
    id: "desert-agave",
    name: "Desert Pebble & Agave",
    category: "Earth & Nature",
    description: "Desert pebble canvas with muted succulent agave sage.",
    swatch: { canvas: "#f6f5f1", card: "#ffffff", accent: "#455a4e" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#f6f5f1",
      bgCard: "#ffffff",
      bgSubtle: "#eae7dd",
      borderColor: "#dedad1",
      textMain: "#262927",
      textMuted: "#5a615d",
      accentPrimary: "#455a4e",
      accentHover: "#35453c",
      accentSubtle: "rgba(69, 90, 78, 0.08)",
      badgeBg: "rgba(69, 90, 78, 0.1)",
      badgeText: "#455a4e",
    },
  },

  // 5. Scholarly Night
  "midnight-emerald": {
    id: "midnight-emerald",
    name: "Midnight Scholar & Emerald Glow",
    category: "Scholarly Night",
    description: "Sophisticated dark midnight slate with luminous emerald green accents.",
    swatch: { canvas: "#0f172a", card: "#1e293b", accent: "#10b981" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#0f172a",
      bgCard: "#1e293b",
      bgSubtle: "#162238",
      borderColor: "#334155",
      textMain: "#f8fafc",
      textMuted: "#94a3b8",
      accentPrimary: "#10b981",
      accentHover: "#059669",
      accentSubtle: "rgba(16, 185, 129, 0.15)",
      badgeBg: "rgba(16, 185, 129, 0.2)",
      badgeText: "#34d399",
    },
  },
  "dark-obsidian-gold": {
    id: "dark-obsidian-gold",
    name: "Dark Obsidian & Academic Gold",
    category: "Scholarly Night",
    description: "Deep obsidian black canvas with warm glowing academic gold accents.",
    swatch: { canvas: "#121316", card: "#1c1e24", accent: "#f59e0b" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#121316",
      bgCard: "#1c1e24",
      bgSubtle: "#181a1f",
      borderColor: "#2e323b",
      textMain: "#f9fafb",
      textMuted: "#9ca3af",
      accentPrimary: "#f59e0b",
      accentHover: "#d97706",
      accentSubtle: "rgba(245, 158, 11, 0.15)",
      badgeBg: "rgba(245, 158, 11, 0.2)",
      badgeText: "#fbbf24",
    },
  },
};

export const DEFAULT_THEME_ID = "cream-terracotta";

export function getTheme(themeId?: string | null): ThemeDefinition {
  if (themeId && ACADEMIC_THEMES[themeId]) {
    return ACADEMIC_THEMES[themeId];
  }
  return ACADEMIC_THEMES[DEFAULT_THEME_ID];
}