export interface ThemeDefinition {
  id: string;
  name: string;
  category: "Archival & Editorial" | "Prestigious Universities" | "Modern Minimalist" | "Earth & Nature" | "Scholarly Night";
  isPinned?: boolean;
  isDark?: boolean;
  description: string;
  swatch: {
    canvas: string;
    card: string;
    accent: string;
  };
  fontHeading: "serif" | "sans";
  cssVars: {
    bgCanvas: string;
    bgCard: string;
    bgSubtle: string;
    borderColor: string;
    textMain: string;
    textMuted: string;
    accentPrimary: string;
    accentHover: string;
    accentSubtle: string;
    badgeBg: string;
    badgeText: string;
  };
}

export const ACADEMIC_THEMES: Record<string, ThemeDefinition> = {
  // ==========================================
  // 1. Archival & Editorial (5 Themes - Light)
  // ==========================================
  "cream-terracotta": {
    id: "cream-terracotta",
    name: "Warm Cream & Terracotta",
    category: "Archival & Editorial",
    isPinned: true,
    description: "Archival book paper canvas with warm terracotta saddle bronze accents.",
    swatch: { canvas: "#faf7f2", card: "#ffffff", accent: "#8a4b2d" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#faf7f2",
      bgCard: "#ffffff",
      bgSubtle: "#f3ede3",
      borderColor: "#e8e2d8",
      textMain: "#2c2b29",
      textMuted: "#666056",
      accentPrimary: "#8a4b2d",
      accentHover: "#723c22",
      accentSubtle: "rgba(138, 75, 45, 0.08)",
      badgeBg: "rgba(138, 75, 45, 0.1)",
      badgeText: "#8a4b2d",
    },
  },
  "sand-forest": {
    id: "sand-forest",
    name: "Muted Sand & Forest Olive",
    category: "Archival & Editorial",
    isPinned: true,
    description: "Organic parchment sand canvas with distinguished British racing green accents.",
    swatch: { canvas: "#f4efe6", card: "#ffffff", accent: "#284e3a" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f4efe6",
      bgCard: "#ffffff",
      bgSubtle: "#ebe3d5",
      borderColor: "#ded6c7",
      textMain: "#242926",
      textMuted: "#525c56",
      accentPrimary: "#284e3a",
      accentHover: "#1f3d2e",
      accentSubtle: "rgba(40, 78, 58, 0.08)",
      badgeBg: "rgba(40, 78, 58, 0.1)",
      badgeText: "#284e3a",
    },
  },
  "parchment-umber": {
    id: "parchment-umber",
    name: "Classical Parchment & Umber",
    category: "Archival & Editorial",
    description: "Ancient library parchment tone with deep raw umber typography.",
    swatch: { canvas: "#f9f6ef", card: "#ffffff", accent: "#634735" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f9f6ef",
      bgCard: "#ffffff",
      bgSubtle: "#efe9dc",
      borderColor: "#e3dcce",
      textMain: "#2e2924",
      textMuted: "#6b6359",
      accentPrimary: "#634735",
      accentHover: "#4e3526",
      accentSubtle: "rgba(99, 71, 53, 0.08)",
      badgeBg: "rgba(99, 71, 53, 0.1)",
      badgeText: "#634735",
    },
  },
  "tuscan-clay": {
    id: "tuscan-clay",
    name: "Tuscan Wheat & Clay",
    category: "Archival & Editorial",
    description: "Sun-drenched Mediterranean paper with warm terracotta brick accents.",
    swatch: { canvas: "#f7f3ec", card: "#ffffff", accent: "#9c5333" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f7f3ec",
      bgCard: "#ffffff",
      bgSubtle: "#ede5d8",
      borderColor: "#ded3c3",
      textMain: "#2d2824",
      textMuted: "#695e54",
      accentPrimary: "#9c5333",
      accentHover: "#7e4024",
      accentSubtle: "rgba(156, 83, 51, 0.08)",
      badgeBg: "rgba(156, 83, 51, 0.1)",
      badgeText: "#9c5333",
    },
  },
  "vellum-sienna": {
    id: "vellum-sienna",
    name: "Monastic Vellum & Burnt Sienna",
    category: "Archival & Editorial",
    description: "Medieval scriptorium vellum with illuminated burnt sienna ink accents.",
    swatch: { canvas: "#f6f1e8", card: "#ffffff", accent: "#a04000" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f6f1e8",
      bgCard: "#ffffff",
      bgSubtle: "#ede4d4",
      borderColor: "#ded3bf",
      textMain: "#2b221a",
      textMuted: "#665545",
      accentPrimary: "#a04000",
      accentHover: "#823400",
      accentSubtle: "rgba(160, 64, 0, 0.08)",
      badgeBg: "rgba(160, 64, 0, 0.1)",
      badgeText: "#a04000",
    },
  },

  // ==========================================
  // 2. Prestigious Universities (6 Themes - Light)
  // ==========================================
  "stone-oxford": {
    id: "stone-oxford",
    name: "Limestone & Oxford Navy",
    category: "Prestigious Universities",
    description: "Architectural cool limestone canvas with collegiate Oxford navy accents.",
    swatch: { canvas: "#f5f6f8", card: "#ffffff", accent: "#1b365d" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f5f6f8",
      bgCard: "#ffffff",
      bgSubtle: "#eaedf2",
      borderColor: "#dbe0e8",
      textMain: "#1e242d",
      textMuted: "#5a6474",
      accentPrimary: "#1b365d",
      accentHover: "#132743",
      accentSubtle: "rgba(27, 54, 93, 0.08)",
      badgeBg: "rgba(27, 54, 93, 0.1)",
      badgeText: "#1b365d",
    },
  },
  "linen-crimson": {
    id: "linen-crimson",
    name: "French Linen & Harvard Crimson",
    category: "Prestigious Universities",
    description: "Refined French linen tone with prestigious Harvard crimson red accents.",
    swatch: { canvas: "#f8f5f0", card: "#ffffff", accent: "#80222f" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f8f5f0",
      bgCard: "#ffffff",
      bgSubtle: "#efeae3",
      borderColor: "#e3dbd2",
      textMain: "#2c2627",
      textMuted: "#695b5c",
      accentPrimary: "#80222f",
      accentHover: "#661a25",
      accentSubtle: "rgba(128, 34, 47, 0.08)",
      badgeBg: "rgba(128, 34, 47, 0.1)",
      badgeText: "#80222f",
    },
  },
  "cambridge-cobalt": {
    id: "cambridge-cobalt",
    name: "Cambridge Cobalt & Slate",
    category: "Prestigious Universities",
    description: "Cool British chalk slate with distinguished Cambridge blue-cobalt accents.",
    swatch: { canvas: "#f2f5f9", card: "#ffffff", accent: "#1e40af" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#f2f5f9",
      bgCard: "#ffffff",
      bgSubtle: "#e4ebf5",
      borderColor: "#d4dfed",
      textMain: "#1e293b",
      textMuted: "#475569",
      accentPrimary: "#1e40af",
      accentHover: "#172554",
      accentSubtle: "rgba(30, 64, 175, 0.08)",
      badgeBg: "rgba(30, 64, 175, 0.1)",
      badgeText: "#1e40af",
    },
  },
  "imperial-purple": {
    id: "imperial-purple",
    name: "Imperial Purple & Ivory",
    category: "Prestigious Universities",
    description: "Regal European university aesthetic with deep amethyst royal purple.",
    swatch: { canvas: "#f9f6fa", card: "#ffffff", accent: "#581c87" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f9f6fa",
      bgCard: "#ffffff",
      bgSubtle: "#f2e9f5",
      borderColor: "#e4d5ea",
      textMain: "#271b2d",
      textMuted: "#634c6e",
      accentPrimary: "#581c87",
      accentHover: "#3b0764",
      accentSubtle: "rgba(88, 28, 135, 0.08)",
      badgeBg: "rgba(88, 28, 135, 0.1)",
      badgeText: "#581c87",
    },
  },
  "ivory-prussian": {
    id: "ivory-prussian",
    name: "Antique Ivory & Prussian Blue",
    category: "Prestigious Universities",
    description: "Prussian naval academy blue with warm antique ivory paper canvas.",
    swatch: { canvas: "#fbf9f4", card: "#ffffff", accent: "#0d3b66" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#fbf9f4",
      bgCard: "#ffffff",
      bgSubtle: "#f3efe3",
      borderColor: "#e5e0d4",
      textMain: "#1a2634",
      textMuted: "#5c6773",
      accentPrimary: "#0d3b66",
      accentHover: "#082642",
      accentSubtle: "rgba(13, 59, 102, 0.08)",
      badgeBg: "rgba(13, 59, 102, 0.1)",
      badgeText: "#0d3b66",
    },
  },
  "vienna-bordeaux": {
    id: "vienna-bordeaux",
    name: "Vienna Porcelain & Bordeaux",
    category: "Prestigious Universities",
    description: "Austrian academy aesthetic with deep royal bordeaux wine accents.",
    swatch: { canvas: "#fcfaf7", card: "#ffffff", accent: "#722f37" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#fcfaf7",
      bgCard: "#ffffff",
      bgSubtle: "#f5eee7",
      borderColor: "#ebdcd6",
      textMain: "#291e20",
      textMuted: "#6b5a5c",
      accentPrimary: "#722f37",
      accentHover: "#551f25",
      accentSubtle: "rgba(114, 47, 55, 0.08)",
      badgeBg: "rgba(114, 47, 55, 0.1)",
      badgeText: "#722f37",
    },
  },

  // ==========================================
  // 3. Modern Minimalist (5 Themes - Light)
  // ==========================================
  "nordic-snow": {
    id: "nordic-snow",
    name: "Nordic Snow & Graphite",
    category: "Modern Minimalist",
    description: "Pure Scandinavian snow canvas with high-contrast graphite typography.",
    swatch: { canvas: "#fcfcfd", card: "#ffffff", accent: "#334155" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#fcfcfd",
      bgCard: "#ffffff",
      bgSubtle: "#f1f5f9",
      borderColor: "#e2e8f0",
      textMain: "#0f172a",
      textMuted: "#64748b",
      accentPrimary: "#334155",
      accentHover: "#1e293b",
      accentSubtle: "rgba(51, 65, 85, 0.08)",
      badgeBg: "rgba(51, 65, 85, 0.1)",
      badgeText: "#334155",
    },
  },
  "notion-sage": {
    id: "notion-sage",
    name: "Notion Slate & Soft Sage",
    category: "Modern Minimalist",
    description: "Productivity monograph paper with soothing sage-slate accents.",
    swatch: { canvas: "#f7f8f7", card: "#ffffff", accent: "#475569" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#f7f8f7",
      bgCard: "#ffffff",
      bgSubtle: "#edf0ed",
      borderColor: "#dfe4df",
      textMain: "#1f2937",
      textMuted: "#6b7280",
      accentPrimary: "#475569",
      accentHover: "#334155",
      accentSubtle: "rgba(71, 85, 105, 0.08)",
      badgeBg: "rgba(71, 85, 105, 0.1)",
      badgeText: "#475569",
    },
  },
  "cashmere-espresso": {
    id: "cashmere-espresso",
    name: "Cashmere & Espresso Noir",
    category: "Modern Minimalist",
    description: "Quiet luxury monograph style with warm cashmere paper and dark espresso.",
    swatch: { canvas: "#f6f3ee", card: "#ffffff", accent: "#3d2e24" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f6f3ee",
      bgCard: "#ffffff",
      bgSubtle: "#ece6dd",
      borderColor: "#ded4c7",
      textMain: "#221c17",
      textMuted: "#63584e",
      accentPrimary: "#3d2e24",
      accentHover: "#281e17",
      accentSubtle: "rgba(61, 46, 36, 0.08)",
      badgeBg: "rgba(61, 46, 36, 0.1)",
      badgeText: "#3d2e24",
    },
  },
  "zinc-steel": {
    id: "zinc-steel",
    name: "Minimal Zinc & Cold Steel",
    category: "Modern Minimalist",
    description: "Architectural grey tones with high-tech cold steel teal accents.",
    swatch: { canvas: "#f4f4f5", card: "#ffffff", accent: "#0f766e" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#f4f4f5",
      bgCard: "#ffffff",
      bgSubtle: "#e4e4e7",
      borderColor: "#d4d4d8",
      textMain: "#18181b",
      textMuted: "#52525b",
      accentPrimary: "#0f766e",
      accentHover: "#115e59",
      accentSubtle: "rgba(15, 118, 110, 0.08)",
      badgeBg: "rgba(15, 118, 110, 0.1)",
      badgeText: "#0f766e",
    },
  },
  "alabaster-slate": {
    id: "alabaster-slate",
    name: "Alabaster & Charred Slate",
    category: "Modern Minimalist",
    description: "Architectural art-gallery minimalist contrast with charred black slate.",
    swatch: { canvas: "#f9fafb", card: "#ffffff", accent: "#27272a" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#f9fafb",
      bgCard: "#ffffff",
      bgSubtle: "#f3f4f6",
      borderColor: "#e5e7eb",
      textMain: "#111827",
      textMuted: "#4b5563",
      accentPrimary: "#27272a",
      accentHover: "#09090b",
      accentSubtle: "rgba(39, 39, 42, 0.08)",
      badgeBg: "rgba(39, 39, 42, 0.1)",
      badgeText: "#27272a",
    },
  },

  // ==========================================
  // 4. Earth & Nature (6 Themes - Light)
  // ==========================================
  "matcha-moss": {
    id: "matcha-moss",
    name: "Japanese Matcha & Moss",
    category: "Earth & Nature",
    description: "Organic Japanese tea paper canvas with deep Kyoto matcha green accents.",
    swatch: { canvas: "#f5f6f2", card: "#ffffff", accent: "#365314" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f5f6f2",
      bgCard: "#ffffff",
      bgSubtle: "#e9ede3",
      borderColor: "#dbe2d2",
      textMain: "#1f2913",
      textMuted: "#556447",
      accentPrimary: "#365314",
      accentHover: "#1a2e05",
      accentSubtle: "rgba(54, 83, 20, 0.08)",
      badgeBg: "rgba(54, 83, 20, 0.1)",
      badgeText: "#365314",
    },
  },
  "pacific-teal": {
    id: "pacific-teal",
    name: "Pacific Deep Teal & Sand",
    category: "Earth & Nature",
    description: "Coastal parchment paper with deep Pacific marine teal accents.",
    swatch: { canvas: "#f2f7f7", card: "#ffffff", accent: "#115e59" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#f2f7f7",
      bgCard: "#ffffff",
      bgSubtle: "#e2efee",
      borderColor: "#cde3e1",
      textMain: "#132a2a",
      textMuted: "#4a6867",
      accentPrimary: "#115e59",
      accentHover: "#042f2e",
      accentSubtle: "rgba(17, 94, 89, 0.08)",
      badgeBg: "rgba(17, 94, 89, 0.1)",
      badgeText: "#115e59",
    },
  },
  "autumn-rust": {
    id: "autumn-rust",
    name: "Autumn Rust & Warm Cedar",
    category: "Earth & Nature",
    description: "Crisp autumn paper canvas with rich burnt cedar wood and rust orange.",
    swatch: { canvas: "#fbf6f3", card: "#ffffff", accent: "#9a3412" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#fbf6f3",
      bgCard: "#ffffff",
      bgSubtle: "#f5ece5",
      borderColor: "#ebddd3",
      textMain: "#2e211a",
      textMuted: "#6b564c",
      accentPrimary: "#9a3412",
      accentHover: "#7c2d12",
      accentSubtle: "rgba(154, 52, 18, 0.08)",
      badgeBg: "rgba(154, 52, 18, 0.1)",
      badgeText: "#9a3412",
    },
  },
  "desert-agave": {
    id: "desert-agave",
    name: "Desert Agave & Terracotta",
    category: "Earth & Nature",
    description: "High-desert warm sand paper with vibrant agave succulent teal.",
    swatch: { canvas: "#f7f5f0", card: "#ffffff", accent: "#0d9488" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#f7f5f0",
      bgCard: "#ffffff",
      bgSubtle: "#ede9e0",
      borderColor: "#ded8cc",
      textMain: "#292621",
      textMuted: "#5e594f",
      accentPrimary: "#0d9488",
      accentHover: "#0f766e",
      accentSubtle: "rgba(13, 148, 136, 0.08)",
      badgeBg: "rgba(13, 148, 136, 0.1)",
      badgeText: "#0d9488",
    },
  },
  "kyoto-cedar": {
    id: "kyoto-cedar",
    name: "Kyoto Hinoki & Warm Cedar",
    category: "Earth & Nature",
    description: "Japanese imperial cedar wood with organic warm paper tone.",
    swatch: { canvas: "#f7f4ed", card: "#ffffff", accent: "#8b4513" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#f7f4ed",
      bgCard: "#ffffff",
      bgSubtle: "#ebe5d8",
      borderColor: "#ded7c7",
      textMain: "#2c251e",
      textMuted: "#63574c",
      accentPrimary: "#8b4513",
      accentHover: "#6e330a",
      accentSubtle: "rgba(139, 69, 19, 0.08)",
      badgeBg: "rgba(139, 69, 19, 0.1)",
      badgeText: "#8b4513",
    },
  },
  "aegean-sand": {
    id: "aegean-sand",
    name: "Aegean Sea & Warm Sand",
    category: "Earth & Nature",
    description: "Mediterranean coastal academic blue with sea-salt limestone canvas.",
    swatch: { canvas: "#f5f7fa", card: "#ffffff", accent: "#006699" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#f5f7fa",
      bgCard: "#ffffff",
      bgSubtle: "#e9edf4",
      borderColor: "#dbe3ec",
      textMain: "#1e293b",
      textMuted: "#64748b",
      accentPrimary: "#006699",
      accentHover: "#004c73",
      accentSubtle: "rgba(0, 102, 153, 0.08)",
      badgeBg: "rgba(0, 102, 153, 0.1)",
      badgeText: "#006699",
    },
  },

  // ==========================================
  // 5. Scholarly Night (8 Themes - Dark Mode)
  // ==========================================
  "midnight-emerald": {
    id: "midnight-emerald",
    name: "Midnight Slate & Emerald",
    category: "Scholarly Night",
    isDark: true,
    description: "Sophisticated dark midnight slate with luminous emerald green accents.",
    swatch: { canvas: "#0f172a", card: "#1e293b", accent: "#10b981" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#0f172a",
      bgCard: "#1e293b",
      bgSubtle: "#162238",
      borderColor: "#334155",
      textMain: "#f8fafc",
      textMuted: "#94a3b8",
      accentPrimary: "#10b981",
      accentHover: "#059669",
      accentSubtle: "rgba(16, 185, 129, 0.15)",
      badgeBg: "rgba(16, 185, 129, 0.2)",
      badgeText: "#34d399",
    },
  },
  "dark-obsidian-gold": {
    id: "dark-obsidian-gold",
    name: "Dark Obsidian & Academic Gold",
    category: "Scholarly Night",
    isDark: true,
    description: "Deep obsidian black canvas with warm glowing academic gold accents.",
    swatch: { canvas: "#121316", card: "#1c1e24", accent: "#f59e0b" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#121316",
      bgCard: "#1c1e24",
      bgSubtle: "#181a1f",
      borderColor: "#2e323b",
      textMain: "#f9fafb",
      textMuted: "#9ca3af",
      accentPrimary: "#f59e0b",
      accentHover: "#d97706",
      accentSubtle: "rgba(245, 158, 11, 0.15)",
      badgeBg: "rgba(245, 158, 11, 0.2)",
      badgeText: "#fbbf24",
    },
  },

  // ==========================================
  // 5. Scholarly Night & Dark Modes (7 Themes)
  // ==========================================
  "dark-slate-white": {
    id: "dark-slate-white",
    name: "Dark Slate & Pure White",
    category: "Scholarly Night",
    isPinned: true,
    isDark: true,
    description: "Deep dark charcoal slate canvas with high-contrast pure white typography and modern technical precision.",
    swatch: { canvas: "#0f172a", card: "#1e293b", accent: "#38bdf8" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#0b1120",
      bgCard: "#1e293b",
      bgSubtle: "#151e2e",
      borderColor: "#334155",
      textMain: "#ffffff",
      textMuted: "#94a3b8",
      accentPrimary: "#38bdf8",
      accentHover: "#0ea5e9",
      accentSubtle: "rgba(56, 189, 248, 0.15)",
      badgeBg: "rgba(255, 255, 255, 0.12)",
      badgeText: "#ffffff",
    },
  },
  "deep-navy-champagne": {
    id: "deep-navy-champagne",
    name: "Royal Navy & Champagne Gold",
    category: "Scholarly Night",
    isDark: true,
    description: "Deep royal maritime navy blue with shimmering champagne star gold.",
    swatch: { canvas: "#0a1128", card: "#131f42", accent: "#f3c969" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#0a1128",
      bgCard: "#131f42",
      bgSubtle: "#0e1836",
      borderColor: "#1e305e",
      textMain: "#f0f4fc",
      textMuted: "#8ca0cb",
      accentPrimary: "#f3c969",
      accentHover: "#d9ae4c",
      accentSubtle: "rgba(243, 201, 105, 0.15)",
      badgeBg: "rgba(243, 201, 105, 0.2)",
      badgeText: "#f3c969",
    },
  },
  "charcoal-copper": {
    id: "charcoal-copper",
    name: "Charcoal & Burnished Copper",
    category: "Scholarly Night",
    isDark: true,
    description: "Industrial engineering dark mode with warm metallic burnished copper.",
    swatch: { canvas: "#161719", card: "#212327", accent: "#d97742" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#161719",
      bgCard: "#212327",
      bgSubtle: "#1c1e22",
      borderColor: "#32353c",
      textMain: "#f4f4f5",
      textMuted: "#a1a1aa",
      accentPrimary: "#d97742",
      accentHover: "#b85c2b",
      accentSubtle: "rgba(217, 119, 66, 0.15)",
      badgeBg: "rgba(217, 119, 66, 0.2)",
      badgeText: "#f09462",
    },
  },
  "forest-nocturne": {
    id: "forest-nocturne",
    name: "Forest Nocturne & Mint Sage",
    category: "Scholarly Night",
    isDark: true,
    description: "Deep nocturnal botanical green with luminous mint sage highlights.",
    swatch: { canvas: "#0c1913", card: "#142820", accent: "#5eead4" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#0c1913",
      bgCard: "#142820",
      bgSubtle: "#10211a",
      borderColor: "#1e3d31",
      textMain: "#f0fdf4",
      textMuted: "#86efac",
      accentPrimary: "#5eead4",
      accentHover: "#2dd4bf",
      accentSubtle: "rgba(94, 234, 212, 0.15)",
      badgeBg: "rgba(94, 234, 212, 0.2)",
      badgeText: "#5eead4",
    },
  },
  "amethyst-twilight": {
    id: "amethyst-twilight",
    name: "Amethyst Twilight & Lilac",
    category: "Scholarly Night",
    isDark: true,
    description: "Intellectual twilight purple with soft radiant lavender and lilac accents.",
    swatch: { canvas: "#13101c", card: "#1d182b", accent: "#c084fc" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#13101c",
      bgCard: "#1d182b",
      bgSubtle: "#171423",
      borderColor: "#2f2746",
      textMain: "#faf5ff",
      textMuted: "#a89bb9",
      accentPrimary: "#c084fc",
      accentHover: "#a855f7",
      accentSubtle: "rgba(192, 132, 252, 0.15)",
      badgeBg: "rgba(192, 132, 252, 0.2)",
      badgeText: "#c084fc",
    },
  },
  "oxford-dark": {
    id: "oxford-dark",
    name: "Oxford Midnight & Electric Cyan",
    category: "Scholarly Night",
    isDark: true,
    description: "Academic midnight cyber-mechanics with glowing electric cyan accents.",
    swatch: { canvas: "#0b132b", card: "#1c2541", accent: "#48cae4" },
    fontHeading: "sans",
    cssVars: {
      bgCanvas: "#0b132b",
      bgCard: "#1c2541",
      bgSubtle: "#121b37",
      borderColor: "#2b3a67",
      textMain: "#edf2f4",
      textMuted: "#8d99ae",
      accentPrimary: "#48cae4",
      accentHover: "#00b4d8",
      accentSubtle: "rgba(72, 202, 228, 0.15)",
      badgeBg: "rgba(72, 202, 228, 0.2)",
      badgeText: "#48cae4",
    },
  },
  "espresso-macchiato": {
    id: "espresso-macchiato",
    name: "Espresso Dark & Cream Crema",
    category: "Scholarly Night",
    isDark: true,
    description: "Warm cafe dark roast with golden crema foam accents and warm typography.",
    swatch: { canvas: "#1b1613", card: "#27201c", accent: "#e6c280" },
    fontHeading: "serif",
    cssVars: {
      bgCanvas: "#1b1613",
      bgCard: "#27201c",
      bgSubtle: "#201a17",
      borderColor: "#3e342d",
      textMain: "#f9f6f0",
      textMuted: "#b0a297",
      accentPrimary: "#e6c280",
      accentHover: "#cca359",
      accentSubtle: "rgba(230, 194, 128, 0.15)",
      badgeBg: "rgba(230, 194, 128, 0.2)",
      badgeText: "#e6c280",
    },
  },
};

export const DEFAULT_THEME_ID = "cream-terracotta";

export function getTheme(themeId?: string | null): ThemeDefinition {
  if (themeId && ACADEMIC_THEMES[themeId]) {
    return ACADEMIC_THEMES[themeId];
  }
  return ACADEMIC_THEMES[DEFAULT_THEME_ID];
}

// ==========================================
// 30 CURATED ACADEMIC FONT PAIRINGS
// ==========================================
export interface FontStyleDefinition {
  id: string;
  name: string;
  category: "Classical Serif" | "Contemporary Serif" | "Modern Technical Sans" | "Monospace & Architectural";
  tag: string;
  headingFont: string;
  bodyFont: string;
  previewSample: string;
  description: string;
}

export const ACADEMIC_FONT_STYLES: Record<string, FontStyleDefinition> = {
  // ------------------------------------------
  // Group 1: Classical & Heritage Serifs (8)
  // ------------------------------------------
  "playfair-merriweather": {
    id: "playfair-merriweather",
    name: "Classical Oxford & Ivy League",
    category: "Classical Serif",
    tag: "High Authority Serif",
    headingFont: "'Playfair Display', Georgia, Cambria, 'Times New Roman', serif",
    bodyFont: "'Merriweather', Georgia, serif",
    previewSample: "Dr. Abhishek Rajput — Structural Impact Mechanics",
    description: "Dramatic contrast with distinguished traditional serifs. Resembles Oxford University Press and Harvard monographs.",
  },
  "eb-garamond": {
    id: "eb-garamond",
    name: "Old Style Roman & Bodleian",
    category: "Classical Serif",
    tag: "Renaissance Scholar",
    headingFont: "'EB Garamond', Cormorant, Garamond, Georgia, serif",
    bodyFont: "'EB Garamond', Georgia, serif",
    previewSample: "Computational Mechanics & Protective Structures",
    description: "Centuries-old humanist scholarly proportions, calligraphic terminal details, and pure academic warmth.",
  },
  "cormorant-garamond": {
    id: "cormorant-garamond",
    name: "Parisian Monograph & Fine Press",
    category: "Classical Serif",
    tag: "Fine Typography",
    headingFont: "'Cormorant Garamond', Garamond, Georgia, serif",
    bodyFont: "'Cormorant Garamond', Georgia, serif",
    previewSample: "High-Rate Dynamic Perforation of Concrete",
    description: "Delicate and exceptionally refined French scholarly serif inspired by 16th-century Claude Garamont originals.",
  },
  "cinzel-academic": {
    id: "cinzel-academic",
    name: "Royal Academy & Monumental",
    category: "Classical Serif",
    tag: "Monumental Dignity",
    headingFont: "'Cinzel', Georgia, serif",
    bodyFont: "system-ui, -apple-system, sans-serif",
    previewSample: "Department of Civil Engineering • IIT Indore",
    description: "Inspired by classical Roman inscriptions and royal collegiate heraldry, imparting profound dignity and stature.",
  },
  "cinzel-decorative": {
    id: "cinzel-decorative",
    name: "Imperial Roman & Heraldic Charter",
    category: "Classical Serif",
    tag: "Ceremonial Charter",
    headingFont: "'Cinzel Decorative', 'Cinzel', Georgia, serif",
    bodyFont: "Georgia, serif",
    previewSample: "Structural & Impact Mechanics Laboratory",
    description: "Ornate classical capitals with flared terminals, ideal for ceremonial faculty titles and distinguished fellowships.",
  },
  "baskervville-scholarly": {
    id: "baskervville-scholarly",
    name: "British Enlightenment & Cambridge",
    category: "Classical Serif",
    tag: "Cambridge Press",
    headingFont: "'Baskervville', Georgia, Cambria, serif",
    bodyFont: "Georgia, serif",
    previewSample: "Constitutive Modeling of Dynamic Impact",
    description: "Revival of John Baskerville's 1757 typeface representing the English Enlightenment and scientific treatises.",
  },
  "castoro-academic": {
    id: "castoro-academic",
    name: "Venetian Renaissance & Scholar's Press",
    category: "Classical Serif",
    tag: "Venetian Humanist",
    headingFont: "'Castoro', Georgia, serif",
    bodyFont: "Georgia, serif",
    previewSample: "Ballistic Resistance of Metamaterial Targets",
    description: "Warm Venetian scholar serif designed under the direction of the Tiro Typeworks academic foundry.",
  },
  "fraunces-editorial": {
    id: "fraunces-editorial",
    name: "Vintage Typographic & Heavy Editorial",
    category: "Classical Serif",
    tag: "Heavy Monograph",
    headingFont: "'Fraunces', Georgia, serif",
    bodyFont: "system-ui, -apple-system, sans-serif",
    previewSample: "Laboratory Facilities & Testing Equipment",
    description: "Expressive modern-vintage serif with organic curves, popular in premium academic book publications.",
  },

  // ------------------------------------------
  // Group 2: Contemporary & Scientific Serifs (8)
  // ------------------------------------------
  "lora-editorial": {
    id: "lora-editorial",
    name: "Modern Literary & Scientific Journal",
    category: "Contemporary Serif",
    tag: "Editorial Polish",
    headingFont: "'Lora', Georgia, serif",
    bodyFont: "system-ui, -apple-system, sans-serif",
    previewSample: "High-Velocity Impact & Ballistic Perforation",
    description: "Contemporary brushed serif engineered for readability on digital screens. Preferred by leading scientific journals.",
  },
  "merriweather-sans": {
    id: "merriweather-sans",
    name: "University Textbook & Digital Scholar",
    category: "Contemporary Serif",
    tag: "Textbook Clarity",
    headingFont: "'Merriweather', Georgia, serif",
    bodyFont: "'Merriweather Sans', system-ui, sans-serif",
    previewSample: "Crashworthiness of Thin-Walled Structures",
    description: "Specifically designed by Eben Sorkin to be pleasant to read on digital displays, even in dense scientific papers.",
  },
  "spectral-academic": {
    id: "spectral-academic",
    name: "Typographic Purity & Scholarly Open",
    category: "Contemporary Serif",
    tag: "Open Scholar",
    headingFont: "'Spectral', Georgia, serif",
    bodyFont: "'Spectral', Georgia, serif",
    previewSample: "Dynamic Mechanical Behavior of Materials",
    description: "Commissioned by Google for reading long documents, Spectral excels in screen and paper academic formatting.",
  },
  "alegreya-humanist": {
    id: "alegreya-humanist",
    name: "Philosophical Treatise & Warmth",
    category: "Contemporary Serif",
    tag: "Humanist Warmth",
    headingFont: "'Alegreya', Georgia, serif",
    bodyFont: "'Alegreya Sans', system-ui, sans-serif",
    previewSample: "Experimental & Numerical Impact Mechanics",
    description: "Chosen as one of the best fonts of the decade by the Association Typographique Internationale (ATypI).",
  },
  "bitter-editorial": {
    id: "bitter-editorial",
    name: "Contemporary Slab & High Contrast",
    category: "Contemporary Serif",
    tag: "Slab Academic",
    headingFont: "'Bitter', Georgia, serif",
    bodyFont: "system-ui, -apple-system, sans-serif",
    previewSample: "Extreme Blast Loading on Civil Structures",
    description: "Balanced slab serif with subtle curvature, designed specifically for rigorous, comfortably legible reading.",
  },
  "literata-monograph": {
    id: "literata-monograph",
    name: "Digital Literature & Journalistic Publishing",
    category: "Contemporary Serif",
    tag: "Publishing Standard",
    headingFont: "'Literata', Georgia, serif",
    bodyFont: "system-ui, -apple-system, sans-serif",
    previewSample: "Axial Crushing of Double-Cell Hollow Tubes",
    description: "Commissioned for long-form reading, Literata brings highest editorial prestige to research publications.",
  },
  "newsreader-academic": {
    id: "newsreader-academic",
    name: "New York Review & Archival Editorial",
    category: "Contemporary Serif",
    tag: "Literary Monograph",
    headingFont: "'Newsreader', Georgia, serif",
    bodyFont: "system-ui, -apple-system, sans-serif",
    previewSample: "Perforation Mechanics of Layered Armor",
    description: "Inspired by 20th-century news periodicals, providing literary depth and smooth, continuous paragraph reading.",
  },
  "noto-serif": {
    id: "noto-serif",
    name: "Global Academic & Polymath Universal",
    category: "Contemporary Serif",
    tag: "Global Science",
    headingFont: "'Noto Serif', Georgia, serif",
    bodyFont: "system-ui, -apple-system, sans-serif",
    previewSample: "International Research Collaborations",
    description: "Google's universal academic typeface, engineered for harmony across mathematical and international typography.",
  },

  // ------------------------------------------
  // Group 3: Modern Technical & STEM Sans (8)
  // ------------------------------------------
  "plus-jakarta": {
    id: "plus-jakarta",
    name: "MIT & Stanford Neo-Grotesque",
    category: "Modern Technical Sans",
    tag: "Clean High-Tech",
    headingFont: "'Plus Jakarta Sans', Inter, system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    previewSample: "Finite Element & SPH Hydrodynamics Modeling",
    description: "Ultra-crisp geometric precision, modern clarity, and high data density. Ideal for modern engineering labs.",
  },
  "space-grotesk": {
    id: "space-grotesk",
    name: "Technical Engineering Mono-Sans",
    category: "Modern Technical Sans",
    tag: "Structural & Ballistics",
    headingFont: "'Space Grotesk', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    previewSample: "Dynamic Crushing & Ballistic Penetration",
    description: "Distinct technological character with structural geometry. Captures the physics and mechanics feel.",
  },
  "inter-clean": {
    id: "inter-clean",
    name: "Pure Digital Research & UI Precision",
    category: "Modern Technical Sans",
    tag: "Maximum Legibility",
    headingFont: "'Inter', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    previewSample: "High-Rate Split Hopkinson Pressure Bar",
    description: "The gold standard of digital typography, featuring tall x-height and exceptional mathematical readability.",
  },
  "dm-sans": {
    id: "dm-sans",
    name: "Modern Geometric & Architectural Clean",
    category: "Modern Technical Sans",
    tag: "Architectural Precision",
    headingFont: "'DM Sans', system-ui, sans-serif",
    bodyFont: "'DM Sans', system-ui, sans-serif",
    previewSample: "Civil Infrastructure & Metamaterial Design",
    description: "Crisp low-contrast geometric sans by Colophon Foundry, delivering architectural sharpness to headings.",
  },
  "outfit-geometric": {
    id: "outfit-geometric",
    name: "Contemporary Digital Laboratory",
    category: "Modern Technical Sans",
    tag: "Modern Geometric",
    headingFont: "'Outfit', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    previewSample: "Shock Waves & Protective Target Panels",
    description: "Friendly yet rigorous geometric proportions, popular in cutting-edge university technology incubators.",
  },
  "fira-sans": {
    id: "fira-sans",
    name: "Mozilla Open Engineering & Clarity",
    category: "Modern Technical Sans",
    tag: "Open Engineering",
    headingFont: "'Fira Sans', system-ui, sans-serif",
    bodyFont: "'Fira Sans', system-ui, sans-serif",
    previewSample: "Non-Linear Material Constitutive Equations",
    description: "Designed by legendary typographer Erik Spiekermann, optimized for technical and engineering documents.",
  },
  "manrope-modern": {
    id: "manrope-modern",
    name: "Clean Structural & Ergonomic Tech",
    category: "Modern Technical Sans",
    tag: "Ergonomic Modern",
    headingFont: "'Manrope', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    previewSample: "Dynamic Energy Absorption Mechanisms",
    description: "Modern semi-geometric sans-serif balancing technical precision with organic human curve geometry.",
  },
  "lexend-clarity": {
    id: "lexend-clarity",
    name: "Cognitive Clarity & High-Speed STEM",
    category: "Modern Technical Sans",
    tag: "Cognitive Reading",
    headingFont: "'Lexend', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    previewSample: "Multiscale Impact Dynamics & Armor Design",
    description: "Empirically designed to reduce visual stress and enhance reading proficiency in technical scientific texts.",
  },

  // ------------------------------------------
  // Group 4: Monospace & Architectural Hybrids (6)
  // ------------------------------------------
  "space-mono": {
    id: "space-mono",
    name: "Computational Hydrocode & Physics",
    category: "Monospace & Architectural",
    tag: "Computational Physics",
    headingFont: "'Space Mono', monospace, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    previewSample: "SPH Particles & Lagrangian Formulations",
    description: "Retro-futuristic computational monospace heading paired with clean sans body text for physics lab identity.",
  },
  "jetbrains-mono": {
    id: "jetbrains-mono",
    name: "High-Performance Code & Algorithms",
    category: "Monospace & Architectural",
    tag: "Algorithms & Code",
    headingFont: "'JetBrains Mono', monospace, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    previewSample: "Finite Element Fortran & Python Solvers",
    description: "Developer-favorite monospace designed specifically for reading complex algorithms, matrices, and code.",
  },
  "ibm-plex-sans": {
    id: "ibm-plex-sans",
    name: "IBM Research Lab & Industrial Heritage",
    category: "Monospace & Architectural",
    tag: "Industrial Science",
    headingFont: "'IBM Plex Sans', system-ui, sans-serif",
    bodyFont: "'IBM Plex Sans', system-ui, sans-serif",
    previewSample: "Pioneering Computational Mechanics at IIT Indore",
    description: "Reflects the golden age of industrial computing and enterprise laboratory research with unmatched clarity.",
  },
  "syne-avantgarde": {
    id: "syne-avantgarde",
    name: "Avant-Garde Structural Mechanics",
    category: "Monospace & Architectural",
    tag: "Design Innovation",
    headingFont: "'Syne', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    previewSample: "Next-Generation Protective Metamaterials",
    description: "Bold, wide architectural letterforms that turn any academic website into a striking contemporary statement.",
  },
  "epilogue-editorial": {
    id: "epilogue-editorial",
    name: "Expressive Modernist Architecture",
    category: "Monospace & Architectural",
    tag: "Modernist Design",
    headingFont: "'Epilogue', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    previewSample: "Structural Resilience in Extreme Environments",
    description: "Distinct contemporary proportions with strong personality, ideal for architecture and civil engineering portals.",
  },
  "karla-grotesque": {
    id: "karla-grotesque",
    name: "Editorial Grotesk & Intellectual",
    category: "Monospace & Architectural",
    tag: "Intellectual Grotesk",
    headingFont: "'Karla', system-ui, sans-serif",
    bodyFont: "'Inter', system-ui, sans-serif",
    previewSample: "Dynamic Mechanical Properties of Alloys",
    description: "Popular grotesque sans featuring charming idiosyncrasies that make scholarly titles memorable and distinctive.",
  },
};

export const DEFAULT_FONT_STYLE_ID = "playfair-merriweather";

export function getFontStyle(styleId?: string | null): FontStyleDefinition {
  if (styleId && ACADEMIC_FONT_STYLES[styleId]) {
    return ACADEMIC_FONT_STYLES[styleId];
  }
  return ACADEMIC_FONT_STYLES[DEFAULT_FONT_STYLE_ID];
}